### ISSUE TITLE
Do you have any plan to support contentful CheckList guide via markdown?

### ISSUE THREAD

**Issue by namtx** [FrigadeHQ/frigade-react#19]
as the title, I think it would be great if Frigade supports markdown as checklist guide content.

**Comment by christianmat** [comment]
@namtx Yes -- we've heard this request from a few folks. We will soon support markdown/html in all string contents. Will update this issue as we go along.

**Comment by christianmat** [comment]
@namtx this is now resolved as of `1.29.2`
